export const areaStoryScenarios: Record<string, string[]> = {
  trabalhista: [
    'Empresa com duvida sobre banco de horas e risco de passivo oculto.',
    'Profissional sem recebimento correto de horas extras recorrentes.',
    'Desligamento com divergencia de verbas rescisorias e prazos.',
    'Gestor precisando revisar politicas internas de jornada e controle.',
    'Empregado com suspeita de desvio de funcao sem ajuste contratual.',
    'Negociacao de acordo trabalhista antes de judicializacao.',
    'Duvida sobre estabilidade em contexto de afastamento medico.',
    'Estrategia para documentacao preventiva em RH de pequena empresa.',
    'Questionamento sobre adicional noturno e reflexos em folha.',
    'Caso hibrido entre conflito individual e necessidade de compliance da empresa.',
  ],
  educacional: [
    'Instituicao revisando regimento e contratos apos atualizacao normativa.',
    'Equipe pedagogica precisando de protocolo para atendimento a familias.',
    'Reorganizacao de fluxos academico-administrativos com risco regulatorio.',
    'Treinamento interno para reduzir falhas operacionais em compliance.',
    'Adequacao de politicas de privacidade em ambiente escolar.',
    'Gestao buscando plano de acao para auditoria institucional.',
    'Conflito entre comunicacao institucional e deveres contratuais com responsaveis.',
    'Implantacao de rotina de evidencias para fiscalizacao futura.',
    'Revisao de termos de uso de imagem e tratamento de dados de alunos.',
    'Projeto de formacao continuada para coordenacao e administrativo.',
  ],
  digital: [
    'Empresa sem mapa de dados pessoais e risco de nao conformidade LGPD.',
    'Incidente digital com necessidade de resposta organizada e registro.',
    'Contrato digital com clausulas frageis sobre responsabilidade de dados.',
    'Equipe comercial tratando dados sem padrao de consentimento adequado.',
    'Instituicao educacional com duvida sobre retencao e descarte de dados.',
    'Negocio precisando estruturar governanca minima de privacidade.',
    'Fluxo de atendimento sem trilha de auditoria para requisicoes de titulares.',
    'Treinamento pratico para reduzir erro humano em operacoes digitais.',
    'Risco reputacional por comunicacao indevida de dados sensiveis.',
    'Caso hibrido entre adequacao LGPD e revisao de processos internos.',
  ],
  familia: [
    'Divorcio com intencao de acordo e protecao patrimonial organizada.',
    'Definicao de guarda e convivencia com foco no melhor interesse da crianca.',
    'Revisao de pensao alimenticia por mudanca de capacidade financeira.',
    'Acordo familiar sem formalizacao juridica adequada.',
    'Organizacao de inventario em cenario de consenso entre herdeiros.',
    'Conflito de comunicacao familiar com risco de escalada judicial.',
    'Protecao de patrimonio em nova composicao familiar.',
    'Ajuste de clausulas em acordo anterior que ficou desatualizado.',
    'Planejamento sucessorio preventivo com foco em previsibilidade.',
    'Caso sensivel que exige conducao tecnica e linguagem humanizada.',
  ],
  consumidor: [
    'Cobranca indevida impactando orcamento mensal e score de credito.',
    'Contrato com clausula abusiva e falta de transparencia na contratacao.',
    'Negativacao irregular com necessidade de correcao rapida.',
    'Falha de servico com prejuizo financeiro relevante.',
    'Fraude em operacao bancaria com documentacao incompleta.',
    'Compra online nao entregue e recusa de reembolso.',
    'Reincidencia de cobranca ja contestada administrativamente.',
    'Conflito com fornecedor em relacao a garantia e vicio oculto.',
    'Caso de consumo com reflexo direto no patrimonio familiar.',
    'Situacao diferente que mistura consumo, contrato e dano moral.',
  ],
  'imoveis-inventario': [
    'Inventario consensual com necessidade de checklist documental.',
    'Partilha amigavel com duvidas sobre formalizacao em cartorio.',
    'Contrato de compra e venda com clausulas de risco patrimonial.',
    'Familia buscando solucao extrajudicial para reduzir desgaste.',
    'Regularizacao de imovel para viabilizar acordo entre herdeiros.',
    'Ajuste de contrato locaticio com foco em seguranca juridica.',
    'Negociacao imobiliaria com necessidade de revisao pre-assinatura.',
    'Divisao de bens com consenso parcial e pontos pendentes.',
    'Documentacao incompleta impedindo avanco do inventario.',
    'Caso atipico que exige estrategia combinando acordo e prevencao.',
  ],
  'planos-saude': [
    'Negativa de procedimento essencial com urgencia medica.',
    'Reajuste elevado sem clareza sobre criterios aplicados.',
    'Recusa de cobertura em exame indicado por especialista.',
    'Cancelamento unilateral com impacto imediato no tratamento.',
    'Duvida sobre carencia em situacao de urgencia e emergencia.',
    'Documentacao medica robusta sem resposta efetiva da operadora.',
    'Necessidade de atuacao rapida para garantir continuidade do cuidado.',
    'Conflito sobre medicamento de alto custo e cobertura contratual.',
    'Revisao de historico de atendimento para definir estrategia inicial.',
    'Caso diferente com combinacao de urgencia, contrato e risco de dano.',
  ],
}
